package mx.com.iusacell.services.miiusacell;

import java.util.LinkedList;
import java.util.List;

import javax.xml.rpc.ServiceException;

import mx.com.iusacell.comun.Servicio;
import mx.com.iusacell.services.miiusacell.vo.AbonoTiempoAireVO;
import mx.com.iusacell.services.miiusacell.vo.Addons;
import mx.com.iusacell.services.miiusacell.vo.AltaCitaVO;
import mx.com.iusacell.services.miiusacell.vo.AltaServicioEtakVO;
import mx.com.iusacell.services.miiusacell.vo.AltaServicioLegacyVO;
import mx.com.iusacell.services.miiusacell.vo.AltaServicioPrepagoLegacyVO;
import mx.com.iusacell.services.miiusacell.vo.BankCardAdditionalInfoVO;
import mx.com.iusacell.services.miiusacell.vo.CardVO;
import mx.com.iusacell.services.miiusacell.vo.CatalogoAbonos;
import mx.com.iusacell.services.miiusacell.vo.CatalogoCaeGeneralVO;
import mx.com.iusacell.services.miiusacell.vo.CatalogoIndicadoresVO;
import mx.com.iusacell.services.miiusacell.vo.CatalogoMovilCaeVO;
import mx.com.iusacell.services.miiusacell.vo.CatalogoTotalesVO;
import mx.com.iusacell.services.miiusacell.vo.CatalogoVO;
import mx.com.iusacell.services.miiusacell.vo.CitasDisponiblesXHorario;
import mx.com.iusacell.services.miiusacell.vo.ClienteRegistroVO;
import mx.com.iusacell.services.miiusacell.vo.ClienteVO;
import mx.com.iusacell.services.miiusacell.vo.ConfiguracionXUsuarioMovilVO;
import mx.com.iusacell.services.miiusacell.vo.ConsultaGenerica;
import mx.com.iusacell.services.miiusacell.vo.ConsultaIndicadores;
import mx.com.iusacell.services.miiusacell.vo.ConsultaOperadorExtendidoVO;
import mx.com.iusacell.services.miiusacell.vo.ConsultaOperadorVO;
import mx.com.iusacell.services.miiusacell.vo.ConsultaParametrosVO;
import mx.com.iusacell.services.miiusacell.vo.ConsultaSrScVO;
import mx.com.iusacell.services.miiusacell.vo.ConsultaWalletGeneralVO;
import mx.com.iusacell.services.miiusacell.vo.ConsumosTablaVO;
import mx.com.iusacell.services.miiusacell.vo.ConsumosTotalesVO;
import mx.com.iusacell.services.miiusacell.vo.ContratarServiciosVO;
import mx.com.iusacell.services.miiusacell.vo.DNCambioVO;
import mx.com.iusacell.services.miiusacell.vo.DNReactivacionVO;
import mx.com.iusacell.services.miiusacell.vo.DNSugeridoVO;
import mx.com.iusacell.services.miiusacell.vo.DatosFacturasVO;
import mx.com.iusacell.services.miiusacell.vo.DatosFocalizacionUsuario;
import mx.com.iusacell.services.miiusacell.vo.DatosFocalizacionUsuarioExtendido;
import mx.com.iusacell.services.miiusacell.vo.DatosFocalizacionVO;
import mx.com.iusacell.services.miiusacell.vo.DatosLogin;
import mx.com.iusacell.services.miiusacell.vo.DatosServiciosAContratarVO;
import mx.com.iusacell.services.miiusacell.vo.DetalleFacturaVO;
import mx.com.iusacell.services.miiusacell.vo.DetalleSaldoVO;
import mx.com.iusacell.services.miiusacell.vo.DetalleTotalesLlamadas;
import mx.com.iusacell.services.miiusacell.vo.DetalleTotalesVO;
import mx.com.iusacell.services.miiusacell.vo.ErrorVO;
import mx.com.iusacell.services.miiusacell.vo.EstadoCuentaVO;
import mx.com.iusacell.services.miiusacell.vo.FacturaVirtualDetalleVO;
import mx.com.iusacell.services.miiusacell.vo.GetCitasPendientesXDNVO;
import mx.com.iusacell.services.miiusacell.vo.GetHorariosDisponiblesCallCenterVO;
import mx.com.iusacell.services.miiusacell.vo.ImagenEquipoVO;
import mx.com.iusacell.services.miiusacell.vo.Mensajes;
import mx.com.iusacell.services.miiusacell.vo.Navegacion;
import mx.com.iusacell.services.miiusacell.vo.ObtenerDetallesServicesClassVO;
import mx.com.iusacell.services.miiusacell.vo.PagoFacturaResponseVO;
import mx.com.iusacell.services.miiusacell.vo.MensajeMailVO;
import mx.com.iusacell.services.miiusacell.vo.NumerosFrecuentesVO;
import mx.com.iusacell.services.miiusacell.vo.ObtenerDescripcionPlanesVO1;
import mx.com.iusacell.services.miiusacell.vo.ObtieneEstadoMunicipioVO;
import mx.com.iusacell.services.miiusacell.vo.ObtienePoblacionesVO;
import mx.com.iusacell.services.miiusacell.vo.PermisosClienteVO;
import mx.com.iusacell.services.miiusacell.vo.Referencia;
import mx.com.iusacell.services.miiusacell.vo.ReprogramacionVO;
import mx.com.iusacell.services.miiusacell.vo.ResponseCancelacionVO;
import mx.com.iusacell.services.miiusacell.vo.ResponseCitaVO;
import mx.com.iusacell.services.miiusacell.vo.ServiciosAdicionalesVO;
import mx.com.iusacell.services.miiusacell.vo.ServiciosBundlesAdicionales;
import mx.com.iusacell.services.miiusacell.vo.ServiciosContratarVO;
import mx.com.iusacell.services.miiusacell.vo.ServiciosDisponiblesVO;
import mx.com.iusacell.services.miiusacell.vo.TarjetaVO;
import mx.com.iusacell.services.miiusacell.vo.TarjetasFrecuentesVO;
import mx.com.iusacell.services.miiusacell.vo.TiposDeAtencionVO;
import mx.com.iusacell.services.miiusacell.vo.UfmiVO;
import mx.com.iusacell.services.miiusacell.vo.WalletsDetalleVO;
import mx.com.iusacell.services.miiusacell.vo.catalogoCambioPlanVO;
import mx.com.iusacell.services.miiusacell.vo.autorizador.TransactionVO;
import mx.com.iusacell.services.miiusacell.vo.messageMail.MessageMailBean;
import mx.com.iusacell.services.miiusacell.vo.messageMail.RespuestaMensajeBean;
import mx.com.iusacell.services.miiusacell.vo.ServicioVO;
import mx.com.iusacell.services.miiusacell.vo.GestionServiciosWS.RespuestaServicios;

public interface ServicesInterface {

	public DatosLogin getDatosUsuario(String user, String pass, String usuario, String token) throws Throwable;
	public DatosFocalizacionUsuario focalizacion(String user, String pass, String usuario, String token) throws Throwable;
	public boolean validaLogin(String user, String pass, String usuario, String password, String token) throws Throwable;
	public int login(String user, String pass, String usuario, String password, int unidadDeNegocio, String token) throws Throwable;
	public ConsumosTablaVO detalleConsumosTabla(String user, String pass, String dn, String tipoEvento, String token) throws Throwable;
	public WalletsDetalleVO walletsDetalle(String user, String pass, String dn, String tipoEvento, String token) throws Throwable;
	public WalletsDetalleVO walletsDetalleMes(String user, String pass, String dn, String tipoEvento, String token) throws Throwable;
	public WalletsDetalleVO walletsDetallePorPeriodo(String user, String pass, String dn,  String fechaIni, String fechaFin, String tipoEvento, String token) throws Throwable;
	public ConsumosTotalesVO detalleConsumosTotales(String user, String pass, String dn, String token) throws Throwable;
	public DetalleTotalesVO walletsTotal(String user, String pass, String dn, String token) throws Throwable;
	public DetalleTotalesLlamadas walletsTotalLlamadas(String user, String pass, String dn, String token) throws Throwable;
	public Mensajes walletsTotalMensajes(String user, String pass, String dn, String token) throws Throwable;
	public Navegacion walletsTotalNavegacion(String user, String pass, String dn, String token) throws Throwable;
	public ObtenerDescripcionPlanesVO1 walletsDescripcionPlan(String user, String pass, String dn, String token) throws Throwable;
	public DetalleTotalesVO walletsTotalPeriodo(String user, String pass, String dn, String fechaIni, String fechaFin,String token) throws Throwable;
	public List<ServiciosContratarVO> consultaServicios(String user, String pass, String sNumeroDN, String token) throws Throwable;
	public ContratarServiciosVO contratarServicios(String user, String pass, String dn, AltaServicioEtakVO datosAltaEtak, AltaServicioLegacyVO datosAlta, AltaServicioPrepagoLegacyVO datosAltaPrepago, String token) throws Throwable;
	public ContratarServiciosVO bajaServicios(String user, String pass, String mdn, String idServicio, AltaServicioLegacyVO datosAlta, String token) throws Throwable;
	public List<DatosServiciosAContratarVO> serviciosAContratar(String user, String pass, String dn, String token) throws Throwable;
	public String registroTarjetas(String user, String pass, TarjetaVO tarjeta, int usuarioId, String token) throws Throwable;
	public String registroNumFrecuentes(String user, String pass,String dn, String nombre, String telefono, int usuarioId, String token) throws Throwable;
	public int editarPerfil(String user, String pass, String dn, String nombre, String apPaterno, String apMaterno, String correo, String password, String fechaNacimiento, String fotografia, int usuarioId, String token) throws Throwable;
	public List<NumerosFrecuentesVO> obtieneNumeros(String user, String pass, String dn, String token) throws Throwable;
	public List<TarjetasFrecuentesVO> obtieneTarjetas(String user, String pass, String dn, String token) throws Throwable;
	public int editarCuenta(String user, String pass, String dn, String password, String passwordAnt, String preguntaSec, String respuestaSec, int usuarioId, String token) throws Throwable;
	public int bajaNumeroFrencuente(String user, String pass, String dn, String telefono, int usuarioId, String token) throws Throwable;
	public int bajaTarjeta(String user, String pass, String dn, int marcaTarjetaId, String numtarjeta, int usuarioID, String token) throws Throwable;
	public String getValorParametro(String user, String pass,int parametro, String token) throws Throwable;
	public List<CatalogoVO> obtenerClavesSensales(String user, String pass, String token) throws Throwable;
	public AltaCitaVO altaCita (String user, String pass, int cveHora, String fecha, String tienda, String suscriptor, String nombre, String apPaterno, String apMaterno, String correo, String comentario, int tipoAtencion, int cveGenerdor, String token)  throws Throwable;
	public List<CitasDisponiblesXHorario> horarioDisponibleXcae (String user, String pass, String cae, int motivo, String token) throws Throwable;
	public int generaPin(String user, String pass, String dn,String pin, int idSericio, String token) throws Throwable;
	public String actualizaFotografiaXUsu(String user, String pass,String dn, String fotografia, int usuarioID,String token) throws Throwable;
	public AbonoTiempoAireVO abonoTiempoAire (String user,String pass, String dn, String dnParaAbono, int anioExpira, String cdgSeguridad, String concepto, Double importe, int mesExpira, String numTarjeta, String tipoTarjeta, String ip, Long secuencia, String password, int tipoPlataforma,  String token) throws Throwable;
	public int reestablecerLlave(String user, String pass, String dn, String preguntaSecreta, String resPreguntaSecreta, int idServicio, int usuarioID, String token) throws Throwable;
	public ReprogramacionVO reprogramacion (String user, String pass, String tecnologia, String t_msisdn, String token) throws Throwable;
	public DNSugeridoVO DNSugerido (String user, String pass, String dn, String cantidad, String localidad, String cveEdoCen, String cveMunCen, String cvePobCen, int compania, String token) throws Throwable;
	public DNCambioVO DNCambio(String user, String pass, String dnActual, String dnNuevo, String cveEdoCen, String cveMunCen, String cvePobCen, String token) throws Throwable;
	public DNReactivacionVO DNSuspensionReactivacion(String user, String pass, String dn, String reason, int tipo, String token) throws Throwable;
	public int eliminaUsuario(String user, String pass, String dn, int isuarioId,String token) throws Throwable;
	public ConsultaOperadorVO consultaOperador(String user, String pass, String dn, String token) throws Throwable;
	public MensajeMailVO enviarCorreoSMS(String user, String pass, String dn, String tipoEvento, String mail, String nombre, int idServicio, String token) throws Throwable;
	public DatosFocalizacionVO datosFocalizacion(String user, String pass, String dn, String token) throws Throwable;
	public ObtenerDescripcionPlanesVO1 obtenerDescripcionPlanes(String user, String pass, String idPlan, String plan, int idElephan, int usuario, String ip, String token) throws Throwable;
	public List<ServiciosDisponiblesVO> serviciosDisponibles(String user, String pass, String UnidadNegocio, String token) throws Throwable;
	public List<ServiciosAdicionalesVO> getServiciosAdicionales(String user, String pass, int version, String idPlan, String token) throws Throwable;
	public List<ObtieneEstadoMunicipioVO> ObtieneEstadosMunicipios(String user, String pass, String dn, String filtro, String token )  throws Throwable;
	public List<ObtienePoblacionesVO> ObtienePoblaciones(String user, String pass,String cveedocen, String pfcvemuncen, String token )  throws Throwable;
	public List<TiposDeAtencionVO> getTiposDeAtencion (String user, String pass, String token) throws Throwable;
	public ImagenEquipoVO getImagenEquipo(String user, String pass, String idEquipo, String descripcionEquipo, String token) throws Throwable;
	public int configuracionXUsuario(String user, String pass, String pcdn, String pcconfiguracion,int piiusaurioid, String token) throws Throwable;
	public DatosFocalizacionUsuarioExtendido focalizacionExtendido(String user, String pass, String usuario, String token) throws Throwable;
	public List<GetCitasPendientesXDNVO> getCitasPendientesXDN(String user, String pass, String dn, String token) throws Throwable;
	public ResponseCitaVO cancelaCitaUsuario(String user, String pass, String folio, String token) throws Throwable;
	public List<ServiciosAdicionalesVO> getServiciosAdicionalesPorDn(String user, String pass, int version, String dn, String token) throws Throwable;
	public List<GetHorariosDisponiblesCallCenterVO> getHorariosDisponiblesCallCenter (String user,String pass, String fecha, String in3, String in4, String token) throws Throwable;
	public CatalogoMovilCaeVO obtieneListaVersionCaeS(String user, String pass, int canal,int idAplicacion,int version, String token) throws Throwable;
	public List<CatalogoCaeGeneralVO> obtieneCae(String user, String pass, int canal,int idAplicacion, String token) throws Throwable;
	public ConsultaOperadorExtendidoVO consultaOperadorExtendido(String user, String pass, String dn, String token) throws Throwable;
	public ConsultaParametrosVO getConsultaParametro(String user, String pass,int parametro, String token) throws Throwable;
	public int actualizaXMLTotales(String user, String pass, String dn, String token) throws Throwable;
	
	public DNCambioVO DNCambioRegistro(String user, String pass, String dnActual, String dnNuevo, String cveEdoCen, String cveMunCen, String cvePobCen, int compania, int sistemaOrigen, String password, String token) throws Throwable;
	public DNReactivacionVO DNSuspensionReactivacionRegistro(String user, String pass, String dn, String reason, int tipo,  int compania, int sistemaOrigen, String password, String token) throws Throwable;
	public ContratarServiciosVO contratarServiciosRegistro(String user, String pass, String dn, AltaServicioEtakVO datosAltaEtak, AltaServicioLegacyVO datosAlta, AltaServicioPrepagoLegacyVO datosAltaPrepago, int compania, int sistemaOrigen,String token) throws Throwable;
	public AbonoTiempoAireVO abonoTiempoAireRegistro(String user,String pass, String dn, String dnParaAbono, int anioExpira, String cdgSeguridad, String concepto, Double importe, int mesExpira, String numTarjeta, String tipoTarjeta, String ip, Long secuencia, String password, int tipoPlataforma, int compania, int sistemaOrigen, String token) throws Throwable;
	public String registroCliente(String user, String pass, ClienteVO datosCliente, int usuarioId, String token) throws Throwable;
	
	public DNCambioVO DNCambioBit(String user, String pass, String dnActual, String dnNuevo, String cveEdoCen, String cveMunCen, String cvePobCen, int compania, int sistemaOrigen, String password, int dispositivo,String token) throws Throwable;
	public DNReactivacionVO DNSuspensionReactivacionBit(String user, String pass, String dn, String reason, int tipo,  int compania, int sistemaOrigen, String password, int dispositivo, String token) throws Throwable;
	public ContratarServiciosVO contratarServiciosBit(String user, String pass, String dn, AltaServicioEtakVO datosAltaEtak, AltaServicioLegacyVO datosAlta, AltaServicioPrepagoLegacyVO datosAltaPrepago, int compania, int sistemaOrigen,int dispositivo,String token) throws Throwable;
	public AbonoTiempoAireVO abonoTiempoAireBit(String user,String pass, String dn, String dnParaAbono, int anioExpira, String cdgSeguridad, String concepto, Double importe, int mesExpira, String numTarjeta, String tipoTarjeta, String ip, Long secuencia, String password, int tipoPlataforma, int compania, int sistemaOrigen, int dispositivo,String token) throws Throwable;
	public AltaCitaVO altaCitaBit (String user, String pass, int cveHora, String fecha, String tienda, String suscriptor, String nombre, String apPaterno, String apMaterno, String correo, String comentario, int tipoAtencion, int cveGenerdor, int compania, int sistemaOrigen,String dn, int dispositivo,String token)  throws Throwable;
	public String registroClienteBit(String user, String pass, ClienteRegistroVO datosCliente, int usuarioId, String token) throws Throwable;
	public ReprogramacionVO reprogramacionBit (String user, String pass, String tecnologia, String t_msisdn, int compania, int sistemaOrigen,int dispositivo,String token) throws Throwable;
	
	public AltaCitaVO altaCitas (String user, String pass, int cveHora, String fecha, String tienda, String suscriptor, String nombre, String apPaterno, String apMaterno, String correo, String comentario, int tipoAtencion, int cveGenerdor, int compania, int sistemaOrigen, int dispositivo, int empresa, String token)  throws Throwable;
	public CatalogoIndicadoresVO indicadores(String user, String pass, ConsultaIndicadores input, String token) throws Throwable;
	public boolean registroApp (String user, String pass, List<ErrorVO> registroErrorr,  String token) throws Throwable;
	public DatosFacturasVO getFacturas(String user, String pass, String dn, String noFacturas, String token) throws Throwable;
	public PagoFacturaResponseVO pagarFactura(String user, String pass, String dn, CardVO tarjeta, int tipoPlataforma, int compania, int sistemaOrigen, int dispositivo, String password, String token) throws Throwable;
	public EstadoCuentaVO desgloseFactura (String user, String pass, String facturaUrl, String token) throws Throwable;
	public MensajeMailVO enviarCorreoSMSURL(String user, String pass, String dn, String tipoEvento, String mail, String nombre, int idServicio, String urlFactura, String token) throws Throwable;
	public MensajeMailVO enviarCorreoFacturaDetalle(String user, String pass, String tipoEvento, int idServicio, String urlFactura,FacturaVirtualDetalleVO facturaVirtualDetalle, String token) throws Throwable;
	public RespuestaMensajeBean utilEnviarCorreo(String user, String pass, String dn, MessageMailBean datos, String token) throws Throwable;
	
	public int setConfiguracionXUsuarioMovil(String user, String pass, String dn, String descripcion, String token) throws Throwable;
	public List<ConfiguracionXUsuarioMovilVO> getConfiguracionXUsuarioMovil(String user, String pass, String dn, String token) throws Throwable;
	public DetalleTotalesVO walletsTotalPlus(String user, String pass, String dn, String tipoEvento, String token) throws Throwable;
	public String reservaPIN(String user, String pass, String dn, String token) throws Throwable;
	public boolean validaPIN(String user, String pass, String dn, String pin, String token) throws Throwable;
	public boolean actualizaContrasenia (String user, String pass, String dn, String pin, String token) throws Throwable;
	public ContratarServiciosVO contrataServicios(String user, String pass, String dn, AltaServicioEtakVO datosAltaEtak, AltaServicioLegacyVO datosAlta, AltaServicioPrepagoLegacyVO datosAltaPrepago, int compania, int sistemaOrigen,int dispositivo,String passsword, String token) throws Throwable;	
	public List<CatalogoTotalesVO> cantidadUsuarios (String user, String pass, String token) throws Throwable;
	public DetalleFacturaVO detalleFactura (String user, String pass, String dn, String facturaUrl, String token) throws Throwable;
	public DetalleSaldoVO detalleSaldo(String user, String pass, String dn, String facturaUrl, String token) throws Throwable;
	public List<CatalogoAbonos> getCatalogoAbonos(String user, String pass, String token) throws Throwable;
	public ContratarServiciosVO bajaServiciosPass(String user, String pass, String mdn, String idServicio, AltaServicioLegacyVO datosAlta, String password, String token) throws Throwable;
	public String generaEnviaPIN(String user, String pass, String dn, String token) throws Throwable;
	public boolean getValidacionPIN(String user, String pass, String dn, String pin, String token) throws Throwable;
	public boolean validaDNPassword(String user, String pass, String dn, String passwordUsuario, String token) throws Throwable;
	public List<PermisosClienteVO>getPermisosXcliente(String user, String pass,String dn, String token) throws Throwable;
	public List<ConsultaWalletGeneralVO> consultaWallets(String user, String pass, String dn,String compania, String token) throws Throwable;
	public List<ServiciosBundlesAdicionales> obtenerServiciosBundles(String user, String pass, int version, String dn, String token) throws Throwable;
	public boolean cambioPlan(String user, String pass, String dn, int idNuevoPlan, int costo, String login, String token) throws Throwable;
	public List<catalogoCambioPlanVO> getCatalogoCambioPlan (String user, String pass, String dn, String compania, String serviceClass, String token) throws ServiceException;
	public boolean activarNumeroFrecuente(String user, String pass, String dn, Addons servicios, List<String> numerosFrecuentes, String login, String token) throws Throwable;
	public int contratarServiciosUnefon(String user, String pass, String dn, Addons servicios, String password, String token) throws Throwable;
	public int bajaServiciosUnefon(String user, String pass, String dn, Addons servicios, String password, String token) throws Throwable;
	
	public String consultaBloqueComun (String user, String pass, String query) throws Throwable;
	public LinkedList<ConsultaGenerica> consultaCursorComun (String user, String pass, String query) throws ServiceException;
	public LinkedList<ConsultaGenerica> consultaQueryComun (String user, String pass, String query) throws ServiceException;
	public String getBitacora (String user, String pass, String filtro, String archivoLog) throws ServiceException;
	public String getBitacoraDir (String user, String pass) throws ServiceException;

	public List<ObtenerDetallesServicesClassVO> obtenerDetallesServiceClass(String user, String pass, String dn,String compania, String token) throws Throwable;
	
	public String SemaphoreSaveCustomerInfo (String user, String pass, String mobileNumber, String customerName, String customerLastName, String customerMaidenName, String bankCardNumber,String cardHolder, String expirationDate, String postalCode, String token)throws ServiceException;
	public String SemaphoreUpdateBankCardInfo (String user, String pass, String mobileNumber, String bankCardNumber,String cardHolder, String expirationDate, String postalCode, String customerName, String customerLastName, String customerMaidenName, String token)throws ServiceException;
	public String SemaphoreDeleteBankCardInfo (String user, String pass, String mobileNumber, String bankCardNumber, String token)throws ServiceException;
	
	public MensajeMailVO enviaSMS(String user, String pass, String dn,String body, int unidadNegocio,String token) throws Throwable;
	public String getIdOperador(String user, String pass, String dn, String token) throws Throwable;
	public AbonoTiempoAireVO abonoTiempoAireBitFP(String user,String pass, String dn, String dnParaAbono, int anioExpira, String cdgSeguridad, String concepto, Double importe, int mesExpira, String numTarjeta, String tipoTarjeta, String ip, Long secuencia, String password, int tipoPlataforma, int compania, int sistemaOrigen, int dispositivo, String fingerPrint, String token) throws Throwable;
	public PagoFacturaResponseVO pagarFacturaFP(String user, String pass, String dn, CardVO tarjeta, int tipoPlataforma, int compania, int sistemaOrigen, int dispositivo, String password, String fingerPrint, String token) throws Throwable;
	public AbonoTiempoAireVO abonoTiempoAireBitFingerP(String user,String pass, String dn, String dnParaAbono, int anioExpira, String cdgSeguridad, String concepto, Double importe, int mesExpira, String numTarjeta, String tipoTarjeta, String ip, Long secuencia, String password, int tipoPlataforma, int compania, int sistemaOrigen, int dispositivo, String email, String fingerPrint, String token) throws Throwable;
	public PagoFacturaResponseVO pagarFacturaFingerP(String user, String pass, String dn, CardVO tarjeta, int tipoPlataforma, int compania, int sistemaOrigen, int dispositivo, String password, String ip, String email, String fingerPrint, String token) throws Throwable;
	public ConsultaSrScVO getConsultaSRSC(String user, String pass, String dn, String token) throws Throwable;
	
	public ResponseCancelacionVO getFolioCancelacion(String user, String pass, String dn, String dnContacto,String strNota,  String token) throws Throwable;
	public UfmiVO getUfmi(String user, String pass, String dn, String token) throws Throwable;
	public List<Referencia> getRefBancarias(String user, String pass, String dn, String facturaUrl, String token) throws Throwable;
	public String getOferta (String user, String pass,  String token) throws Throwable;
	public String getPuntos (String user, String pass, int  idFamilia, String idPlan, String token) throws Throwable;
	public List<ServicioVO> consultaCompraPaqServicios(String user, String pass, String idPlan, String operador, String tipoOferta, String token)  throws Throwable;
	
	public RespuestaServicios operacionServicioPaq(String user, String pass, String idLinea, final String passAutorizacion, int tipo, Servicio[] servicios, String token) throws Throwable;
	public AbonoTiempoAireVO buyProductsOnline(String user,String pass, TransactionVO transaction, String token) throws Throwable;
	public BankCardAdditionalInfoVO getAditionalCardInfo(String user, String pass,String prefix, String token) throws Throwable;
}
